from log_parser.commands.stats.statistics.number_of_requests import NumberOfRequests
from log_parser.commands.stats.statistics.number_of_statuses import NumberOfStatuses
from log_parser.commands.stats.statistics.requests_per_second import RequestsPerSecond
from log_parser.commands.stats.statistics.average_response_size import AverageResponseSize
